#+Title:Chef Box: Chef Vagrant Boxes & Playground
#+AUTHOR:Tim Dysinger
#+EMAIL:tim@dysinger.net
#+DATE:2011-06-26

This project enables you to automatically build a complete set of
[[http://www.ubuntu.com/][Ubuntu]] [[http://vagrantup.com][Vagrant]] Boxes for use with [[http://vagrantup.com][Vagrant]].  The boxes are built with
the [[http://wiki.opscode.com/display/chef/Package%2BInstallation%2Bon%2BDebian%2Band%2BUbuntu][Official OpsCode Chef 0.10 Ubuntu Packages]] baked in.  This means
you can start either a Chef Server or Client Node easily at boot time.

Also included in this project is the Vagrant scaffolding to launch a
Chef cluster on your Desktop.  The default 'vagrant up' starts a Chef
Server & 2 Chef Client Nodes.  The nodes are setup to automatically
join the Chef cluster.  You can practice your cookbook, search, knife
and shef skills really easily with 3 disposable nodes.  See the
examples below for more info.

You can also merge the contents of this project into your existing
[[https://github.com/opscode/chef-repo][Chef Repo]] and record, as an artifact in your git repository, how you
built your Vagrant Box instead of it being mystery-meat from the
interweb cache.

* Requirements

  - [[http://www.virtualbox.org/wiki/Downloads][VirtualBox]] 4.0.8
  - [[http://rvm.beginrescueend.com/][RVM]] latest

* Setup

  #+BEGIN_SRC: sh
gem install bundler
bundle install
  #+END_SRC

* Build

  Example: Build a Natty 64bit Box

  #+BEGIN_SRC: sh
rake box:natty64
  #+END_SRC

  Example: Build a LTS Lucid 32bit Box

  #+BEGIN_SRC: sh
rake box:lucid32
  #+END_SRC

  Example: Build All Boxes

  #+BEGIN_SRC: sh
rake box:all
  #+END_SRC

* Launch

  Example: 1 Chef Server & 2 Chef Client Nodes (default)

  #+BEGIN_SRC: sh
vagrant up
  #+END_SRC

  Example: 1 Chef Server & 1 Chef Client Node

  #+BEGIN_SRC: sh
vagrant up chef.vm
vagrant up node0.vm
  #+END_SRC

* Knife

*** Node

    Example: Works Anywhere (Host or Guest)

    #+BEGIN_SRC: sh
knife node list
knife node show chef.vm
    #+END_SRC

*** Search

    Example: Works Anywhere (Host or Guest)

    #+BEGIN_SRC: sh
knife search node "name:chef*.vm"
knife search node "name:node*.vm"
    #+END_SRC

*** SSH

    Example: Works Anywhere (Host or Guest)

    #+BEGIN_SRC: sh
knife ssh "*:*" "date" -a ip -x vagrant -i .ssh/id_rsa --no-host-key-verify
    #+END_SRC

* License [[LICENSE][Apache 2]]
